SELECT
    VENDORID,
    PICKUP_DATETIME,
    PICKUP_MINUTE,
    PICKUP_HEURE,
    PICKUP_JOUR,
    PICKUP_MOIS,
    PICKUP_ANNEE,
    DROPOFF_DATETIME,
    DROPOFF_MINUTE,
    DROPOFF_HEURE,
    DROPOFF_JOUR,
    DROPOFF_MOIS,
    DROPOFF_ANNEE,
    PASSENGER_COUNT,
    TRIP_DISTANCE,
    RATECODEID,
    STORE_AND_FWD_FLAG,
    PULOCATIONID,
    DOLOCATIONID,
    PAYMENT_TYPE,
    FARE_AMOUNT,
    EXTRA,
    MTA_TAX,
    TIP_AMOUNT,
    TOLLS_AMOUNT,
    IMPROVEMENT_SURCHARGE,
    TOTAL_AMOUNT,
    CONGESTION_SURCHARGE,
    AIRPORT_FEE,
    CBD_CONGESTION_FEE
FROM {{ source('raw', 'yellow_taxi_trips_1') }}
WHERE
      FARE_AMOUNT >= 0
  AND TOTAL_AMOUNT >= 0
  AND TRIP_DISTANCE BETWEEN 0.1 AND 100
  AND PULOCATIONID IS NOT NULL
  AND DOLOCATIONID IS NOT NULL