-- code modif time stamp

SELECT 
    VENDORID,
    
    -- Conversion du timestamp microsecondes en TIMESTAMP Snowflake
    -- Puis extraction des éléments souhaités
    TO_TIMESTAMP_NTZ(TPEP_PICKUP_DATETIME / 1000000) AS PICKUP_DATETIME,
    EXTRACT(MINUTE FROM TO_TIMESTAMP_NTZ(TPEP_PICKUP_DATETIME / 1000000)) AS PICKUP_MINUTE,
    EXTRACT(HOUR FROM TO_TIMESTAMP_NTZ(TPEP_PICKUP_DATETIME / 1000000)) AS PICKUP_HEURE,
    EXTRACT(DAY FROM TO_TIMESTAMP_NTZ(TPEP_PICKUP_DATETIME / 1000000)) AS PICKUP_JOUR,
    EXTRACT(MONTH FROM TO_TIMESTAMP_NTZ(TPEP_PICKUP_DATETIME / 1000000)) AS PICKUP_MOIS,
    EXTRACT(YEAR FROM TO_TIMESTAMP_NTZ(TPEP_PICKUP_DATETIME / 1000000)) AS PICKUP_ANNEE,

    TO_TIMESTAMP_NTZ(TPEP_DROPOFF_DATETIME / 1000000) AS DROPOFF_DATETIME,
    EXTRACT(MINUTE FROM TO_TIMESTAMP_NTZ(TPEP_DROPOFF_DATETIME / 1000000)) AS DROPOFF_MINUTE,
    EXTRACT(HOUR FROM TO_TIMESTAMP_NTZ(TPEP_DROPOFF_DATETIME / 1000000)) AS DROPOFF_HEURE,
    EXTRACT(DAY FROM TO_TIMESTAMP_NTZ(TPEP_DROPOFF_DATETIME / 1000000)) AS DROPOFF_JOUR,
    EXTRACT(MONTH FROM TO_TIMESTAMP_NTZ(TPEP_DROPOFF_DATETIME / 1000000)) AS DROPOFF_MOIS,
    EXTRACT(YEAR FROM TO_TIMESTAMP_NTZ(TPEP_DROPOFF_DATETIME / 1000000)) AS DROPOFF_ANNEE,
    
    PASSENGER_COUNT,
    TRIP_DISTANCE,
    RATECODEID,
    STORE_AND_FWD_FLAG,
    PULOCATIONID,
    DOLOCATIONID,
    PAYMENT_TYPE,
    FARE_AMOUNT,
    EXTRA,
    MTA_TAX,
    TIP_AMOUNT,
    TOLLS_AMOUNT,
    IMPROVEMENT_SURCHARGE,
    TOTAL_AMOUNT,
    CONGESTION_SURCHARGE,
    AIRPORT_FEE,
    CBD_CONGESTION_FEE

FROM {{ source('raw', 'yellow_taxi_trips') }}
